"""Application configuration via pydantic-settings.

Required env vars are validated on first access. get_settings() returns
a cached singleton — Settings() is constructed once per process.

Runtime overrides from PATCH /admin/config are persisted to
config_overrides.json and re-applied on startup, making them
survive restarts.

Config loading is synchronous and must complete before async request
paths begin. The module-level lock guards the first-access race condition.
"""

from __future__ import annotations

import json
import threading
from contextvars import ContextVar
from pathlib import Path

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

# Module-level singleton
_settings: Settings | None = None

# Per-session effective settings overlay. When set (inside a request bound to a
# session that has config_overrides), get_settings() returns this instead of the
# global singleton, so all ~54 get_settings() call sites become session-aware
# transparently. Default None == today's behavior (global singleton).
_session_settings_ctx: ContextVar["Settings | None"] = ContextVar(
    "session_settings", default=None
)

# Fields a per-session X-Session-Config header may NOT override. /v1/chat/completions
# is unauthenticated, so a client must not be able to redirect upstream traffic or
# override secrets/paths for their session. Everything else is settable per-session.
SESSION_CONFIG_DENYLIST: frozenset[str] = frozenset({
    "upstream_base_url",
    "upstream_api_url",
    "upstream_api_key",
    "extractor_base_url",
    "extractor_api_key",
    "curator_base_url",
    "curator_api_key",
    "embedding_base_url",
    "embedding_api_key",
    "memory_api_url",
    "memory_api_key",
    "admin_token",
    "ladybug_db_path",
})

# Resolve .env relative to this file's directory (archolith_proxy/),
# then walk up one level to the project root. This ensures .env loads
# correctly regardless of the process working directory.
_PROJECT_ROOT = Path(__file__).parent.parent
_ENV_FILE = str(_PROJECT_ROOT / ".env")
_OVERRIDES_FILE = _PROJECT_ROOT / "config_overrides.json"

# In-memory snapshot of base env values (before overrides applied)
_base_values: dict[str, object] = {}

# Lock guarding _settings and _base_values during initialization
_settings_lock = threading.Lock()


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=_ENV_FILE,
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Upstream API
    upstream_base_url: str = "https://api.deepseek.com/v1"
    upstream_api_key: str = ""

    # Extraction model
    extractor_base_url: str = "https://api.openai.com/v1"
    extractor_api_key: str = ""
    extractor_model: str = "gpt-4.1-mini"

    # Embeddings
    embedding_base_url: str = "https://api.openai.com/v1"
    embedding_api_key: str = ""
    embedding_model: str = "text-embedding-3-small"

    # Session graph (Neo4j — label-based isolation in default database)
    session_neo4j_uri: str = "bolt://localhost:7687"
    session_neo4j_database: str = "neo4j"
    session_neo4j_user: str = "neo4j"
    session_neo4j_password: str = ""

    # Proxy settings
    proxy_port: int = 9800
    coherence_tail_size: int = 10
    max_tail_messages: int = 20
    context_token_budget: int = 15000
    max_rewritten_tokens: int = 24000   # Hard ceiling on rewritten payload tokens (0 = no ceiling)
    session_ttl_hours: int = 24
    cold_start_turns: int = 3
    cold_start_token_threshold: int = 20000

    # Savings-ratio gate: only rewrite when it actually saves meaningful tokens.
    # Calibrated for the structural token estimator (token_accounting): the gate now
    # keys on structural tokens (tools + framing), which run larger than the old
    # content-only estimate. The structural estimate still undercounts actual upstream
    # by ~10.7%, so these are kept conservative — requests that pass are genuinely
    # large. min_input_tokens raised 50K -> 55K to offset structural undercounting;
    # min_savings_ratio raised 0.20 -> 0.25 because tool overhead inflates apparent
    # savings (it does not disappear on rewrite).
    assembly_min_savings_ratio: float = 0.25  # Skip rewriting if savings < 25%
    assembly_min_input_tokens: int = 55000    # Don't rewrite below 55K input tokens

    # Embedding-driven retrieval
    embedding_enabled: bool = False

    # Context compaction (overflow fallback)
    compaction_enabled: bool = False

    # Query rewriting for ambiguous messages (resolves pronouns before embedding)
    query_rewrite_enabled: bool = False

    # Session recall as proxy-intercepted tool (injects __archolith_recall)
    session_recall_tool_enabled: bool = False

    # Agent-initiated synthetic tools (recall_session_work, recall_files_read)
    # Injects two tool definitions that the model can call to get structured
    # summaries of session work and files accessed. Results are generated by
    # the proxy from trace store + graph backend -- never forwarded upstream.
    synthetic_tools_enabled: bool = False

    # Synthetic tool circuit breaker — prevents runaway re-injection loops
    synthetic_circuit_max_consecutive: int = 3     # consecutive failures before cooldown
    synthetic_circuit_cooldown_s: float = 300.0   # cooldown duration in seconds
    synthetic_circuit_max_total: int = 10          # total failures before session-lifetime disable

    # Hard token cap per session — stop context management when exceeded
    max_input_tokens_per_session: int = 2_000_000  # 0 = unlimited
    session_token_budget_action: str = "passthrough"  # "passthrough" (forward raw) or "reject"

    # Per-tool extraction dispatch (class-per-tool instead of single generic LLM call)
    per_tool_extraction_enabled: bool = False
    extractor_llm_concurrency: int = 3  # max concurrent LLM-backed extractor calls (turn-level excluded)

    # Output filtering for outbound tool-role messages (via archolith_filter).
    # Reads the FILTER_ENABLED env var.
    filter_enabled: bool = False

    # Retry / resilience
    upstream_max_retries: int = 3
    upstream_retry_backoff_base_s: float = 0.5
    neo4j_max_retries: int = 3
    neo4j_retry_backoff_base_s: float = 1.0
    assembly_latency_budget_ms: int = 150

    # Graph backend selection
    graph_backend: str = "neo4j"  # "neo4j" or "ladybug"
    ladybug_db_path: str = str(Path(__file__).parent.parent / "data" / "context.lbug")
    ladybug_max_concurrent: int = 8
    # When True, abort startup if a configured graph backend fails to initialize
    # instead of serving in a silently-degraded (passthrough-only) state.
    require_graph_on_startup: bool = False

    # Optional: promotion to long-term memory
    memory_api_url: str = "http://localhost:8200"
    memory_api_key: str = ""
    promotion_enabled: bool = False

    # Memory engine configuration (JSON array of engine configs)
    # See archolith_proxy/memory/models.py MemoryEngineConfig for schema
    memory_engines_json: str = ""  # JSON array of engine config dicts

    # Promotion policy defaults
    promotion_min_confidence: float = 0.9
    promotion_dry_run: bool = False  # If True, generate records but don't write

    # File content cache
    file_cache_enabled: bool = True
    file_cache_max_file_bytes: int = 500_000  # skip caching files larger than this
    file_cache_ttl_turns: int = 50  # evict entries older than this many turns
    file_cache_max_entries: int = 200  # evict oldest entries if over this count

    # Maximum active facts fetched for dedup, assembly, and recall.
    # Higher values improve dedup coverage in long sessions but increase
    # per-turn latency.  Needs a typed-pool redesign for proper fix.
    fact_pool_limit: int = 200

    # Workspace allowlist for prefetch_file / get_file_lines.
    # Comma-separated directory prefixes the curator LLM may read.
    # Empty list = unrestricted (backward compat).
    prefetch_allowed_roots: list[str] = []

    # Transparent native Read call interception — serves Read results from file cache
    # when the file has been previously read this session. Rides on synthetic_tools_enabled.
    native_read_intercept_enabled: bool = True

    # Context assembly aggressiveness
    # B: drop the entire middle when assembled context is present — the assembly
    #    digest replaces raw history; no need to keep compressed turns alongside it.
    #    Default False (backward-compatible); set True for experiment B.
    drop_middle_on_assembly: bool = False

    # C: tighter assembled-context block — override the fact/overview budget for
    #    short sessions where a 15K block is proportionally too large.
    #    When 0 (default), context_token_budget is used unchanged.
    short_session_context_budget: int = 0

    # Curator LLM — active context curation via tool-calling loop
    curator_enabled: bool = False
    curator_model: str = ""             # defaults to extractor_model if empty
    curator_base_url: str = ""          # defaults to extractor_base_url if empty
    curator_api_key: str = ""           # defaults to extractor_api_key if empty
    curator_max_iterations: int = 6
    curator_latency_budget_ms: int = 6000   # hard timeout; falls back to heuristic

    # Agent-solo turn compression — mechanical savings on tool-call continuations
    # without an LLM call.  Each toggle is independent; combine for maximum effect.
    agent_solo_shrink_enabled: bool = False      # A: shrink all tool results to a token budget
    agent_solo_dedup_enabled: bool = False        # B: replace byte-identical tool results with compact markers
    agent_solo_compress_middle_enabled: bool = False  # C: compress compressible tool results in older turns
    agent_solo_shrink_max_tokens: int = 2000     # per-result token cap for strategy A (~4 chars/tok, fuzzy)
    agent_solo_min_input_tokens: int = 8000      # skip compression below this input size
    agent_solo_dump_payloads: bool = False        # dump agent-solo payloads to data/agent_solo_payloads/

    # Briefing staleness threshold — how many turns before a briefing is considered
    # too stale to use (0 = only fresh briefings, 1 = briefing from 1 turn ago ok, etc.)
    briefing_max_staleness: int = 2

    # Two-pass curator — background pass (same bot, generous iteration budget)
    background_pass_enabled: bool = False
    background_pass_max_iterations: int = 12
    background_pass_debounce_ms: int = 2000  # wait for extraction before running
    background_pass_latency_budget_ms: int = 30_000  # hard timeout for background pass

    # Two-curator mode (prepper + assembler) — replaces the single-bot two-pass
    # when curation_mode="two_curator". The prepper runs in the background with
    # its own model config and tool set. The assembler runs inline with a
    # minimal tool set and tight iteration budget.
    curation_mode: str = "two_pass"  # "two_pass" | "two_curator"

    # Prepper (background curator) — defaults to curator_model if empty
    prepper_model: str = ""
    prepper_base_url: str = ""
    prepper_api_key: str = ""
    prepper_max_iterations: int = 12
    prepper_debounce_ms: int = 2000
    prepper_latency_budget_ms: int = 30_000

    # Assembler (fast inline formatter) — defaults to curator_model if empty
    assembler_model: str = ""
    assembler_base_url: str = ""
    assembler_api_key: str = ""
    assembler_max_iterations: int = 2
    assembler_latency_budget_ms: int = 3000

    # Pricing — per-million-token rates for cost estimation on dashboard.
    # Defaults to DeepSeek V4-Flash pricing. Override for other models.
    pricing_input_per_million: float = 0.14       # $/M input tokens (cache miss)
    pricing_input_cached_per_million: float = 0.0028  # $/M input tokens (cache hit)
    pricing_output_per_million: float = 0.28      # $/M output tokens

    # Trace persistence — when set, turn traces are appended as JSONL files
    # under this directory (one file per session: <session_id>.jsonl).
    # Without this, traces are memory-only and lost on restart.
    trace_dir: str = ""

    # Trace retention — delete JSONL trace files older than this many days.
    # When 0 (default), no automatic cleanup. Cleanup runs at proxy startup.
    trace_retention_days: int = 0

    # Admin/operator token for protecting non-proxy surfaces
    # When empty (default), admin endpoints are open (localhost-only assumption).
    # When set, all operator endpoints require X-Admin-Token or Authorization: Bearer matching this value.
    admin_token: str = ""
    # Escape hatch: when True, an empty admin_token leaves admin endpoints open
    # even to non-loopback peers. Default False — empty token is loopback-only.
    admin_allow_open_nonlocal: bool = False

    # Plugin enable/disable — comma-separated plugin IDs.
    # PLUGINS_ENABLED: when non-empty, only listed plugins activate.
    #   When empty (default), all installed plugins activate unless disabled.
    # PLUGINS_DISABLED: always blocks the listed plugin IDs, even if listed in PLUGINS_ENABLED.
    plugins_enabled: str = ""
    plugins_disabled: str = ""

    @property
    def upstream_api_url(self) -> str:
        """Full upstream API base URL (ensures no trailing slash issues)."""
        return self.upstream_base_url.rstrip("/")

    @field_validator("upstream_api_key")
    @classmethod
    def _warn_empty_upstream_key(cls, v: str) -> str:
        if not v:
            import structlog
            structlog.get_logger().warning(
                "UPSTREAM_API_KEY is empty — proxy will fail on upstream calls. "
                "Set UPSTREAM_API_KEY in .env or environment."
            )
        return v

    @field_validator("upstream_base_url")
    @classmethod
    def _validate_upstream_url(cls, v: str) -> str:
        if not v.startswith(("http://", "https://")):
            raise ValueError(f"UPSTREAM_BASE_URL must start with http:// or https://, got: {v}")
        return v

    @field_validator("proxy_port")
    @classmethod
    def _validate_port(cls, v: int) -> int:
        if not (1 <= v <= 65535):
            raise ValueError(f"PROXY_PORT must be 1-65535, got: {v}")
        return v

    def check_required_for_graph(self) -> list[str]:
        """Return list of missing env vars required for graph features."""
        missing = []
        if not self.session_neo4j_password:
            missing.append("SESSION_NEO4J_PASSWORD")
        if not self.extractor_api_key:
            missing.append("EXTRACTOR_API_KEY")
        return missing

    def check_required_for_proxy(self) -> list[str]:
        """Return list of missing env vars required for basic proxy."""
        missing = []
        if not self.upstream_api_key:
            missing.append("UPSTREAM_API_KEY")
        return missing


def _get_global_settings() -> Settings:
    """Return the process-global settings singleton (no session overlay)."""
    global _settings, _base_values
    if _settings is None:
        with _settings_lock:
            # Double-check pattern: another thread may have initialized while waiting
            if _settings is None:
                _settings = Settings()
                # Snapshot base values before applying overrides
                _base_values = {k: getattr(_settings, k) for k in _settings.model_fields}
                # Apply persisted overrides from config_overrides.json
                _apply_overrides(_settings)
    return _settings


def get_settings() -> Settings:
    """Return the effective settings for the current context.

    If a per-session overlay is active (set via set_session_settings during a
    request bound to a session that has config_overrides), return it. Otherwise
    return the process-global singleton. This keeps all call sites unchanged while
    making them session-aware when an overlay is present.
    """
    overlay = _session_settings_ctx.get()
    if overlay is not None:
        return overlay
    return _get_global_settings()


def build_effective_settings(overrides: dict[str, object]) -> Settings:
    """Build a per-session Settings from the global base + (filtered) overrides.

    Precedence: session overrides > global config_overrides.json > env > defaults.
    The global singleton already encodes env + config_overrides.json, so we copy it
    and layer the session overrides on top. Denylisted fields are ignored.
    """
    base = _get_global_settings()
    effective = base.model_copy()
    for key, value in (overrides or {}).items():
        if key in SESSION_CONFIG_DENYLIST:
            continue
        if not hasattr(effective, key):
            continue
        try:
            expected_type = type(getattr(effective, key))
            setattr(effective, key, expected_type(value) if not isinstance(value, expected_type) else value)
        except (ValueError, TypeError):
            continue
    return effective


def set_session_settings(settings: "Settings | None"):
    """Set the per-session settings overlay for the current context.

    Returns the ContextVar Token; pass it to reset_session_settings in a finally
    block to restore the prior overlay. Set None to explicitly run with no overlay.
    """
    return _session_settings_ctx.set(settings)


def reset_session_settings(token) -> None:
    """Restore the per-session overlay to its prior value (pair with set_session_settings)."""
    try:
        _session_settings_ctx.reset(token)
    except (ValueError, LookupError):
        pass


def reset_settings() -> None:
    """Reset the cached settings — used in tests."""
    global _settings, _base_values
    with _settings_lock:
        _settings = None
        _base_values = {}


def _read_overrides() -> dict[str, object]:
    """Read persisted runtime overrides from config_overrides.json."""
    try:
        if _OVERRIDES_FILE.exists():
            return json.loads(_OVERRIDES_FILE.read_text(encoding="utf-8"))
    except Exception:
        pass
    return {}


def _write_overrides(updates: dict[str, object]) -> None:
    """Merge the given updates into config_overrides.json and persist.

    If the file can't be written, log a warning and continue with
    in-memory-only changes.
    """
    import structlog
    logger = structlog.get_logger()
    current = _read_overrides()
    current.update(updates)
    try:
        _OVERRIDES_FILE.write_text(
            json.dumps(current, indent=2, default=str), encoding="utf-8"
        )
        logger.info("config_overrides_persisted", file=str(_OVERRIDES_FILE), keys=list(updates.keys()))
    except Exception as e:
        logger.warning("config_overrides_write_failed", error=str(e))


def _apply_overrides(settings: Settings) -> None:
    """Apply persisted runtime overrides to a Settings instance."""
    overrides = _read_overrides()
    for key, value in overrides.items():
        if hasattr(settings, key):
            try:
                expected_type = type(getattr(settings, key))
                setattr(settings, key, expected_type(value))
            except (ValueError, TypeError):
                pass


def get_settings_delta() -> dict[str, dict[str, object]]:
    """Return the difference between base env values and current settings.

    Returns: {"base": {...}, "current": {...}, "overridden": [...]}
    """
    global _base_values
    settings = get_settings()
    base = _base_values
    current = {k: getattr(settings, k) for k in settings.model_fields}
    overridden = [k for k in current if base.get(k) != current.get(k)]
    return {"base": base, "current": current, "overridden": overridden}


# Fields excluded from config snapshots (secrets, connection strings, paths
# that leak host info, pricing constants that don't affect proxy behavior).
_SNAPSHOT_EXCLUDE = frozenset({
    "upstream_api_key", "extractor_api_key", "embedding_api_key",
    "curator_api_key", "session_neo4j_password", "memory_api_key",
    "admin_token",
    "upstream_base_url", "extractor_base_url", "embedding_base_url",
    "curator_base_url", "prepper_base_url", "prepper_api_key",
    "assembler_base_url", "assembler_api_key",
    "session_neo4j_uri", "session_neo4j_database",
    "session_neo4j_user", "memory_api_url",
    "ladybug_db_path", "trace_dir", "memory_engines_json",
    "pricing_input_per_million", "pricing_input_cached_per_million",
    "pricing_output_per_million",
})


def snapshot_config() -> dict[str, object]:
    """Return a dict of active feature flags and key thresholds.

    Excludes secrets, connection URIs, and pricing constants.  Intended for
    persisting in the trace so session grading can reconstruct which proxy
    features were enabled.
    """
    settings = get_settings()
    return {
        k: v
        for k, v in settings.model_dump().items()
        if k not in _SNAPSHOT_EXCLUDE
    }
