"""Per-session curator state — caches last successful curator result + briefing.

The inline curator starts from scratch every turn, re-discovering the same
files and facts each time. This module caches the last successful result so
the curator prompt can say "you already fetched X, Y, Z — focus on what
changed" and cut 1-2 iterations off the typical run.

The two-pass curator extends this with a SessionBriefing cache: the background
pass writes a briefing, the inline pass reads it. Briefings are in-memory only
and considered fresh when source_turn >= current_turn - 1.

In-memory only — lost on restart, which is fine since the curator rebuilds
from the graph/cache backend anyway.
"""

from __future__ import annotations

import asyncio
import time
from dataclasses import dataclass, field

from archolith_proxy.curator.briefing import SessionBriefing


@dataclass(frozen=True)
class CuratorSnapshot:
    """Frozen snapshot of a successful curator run for the next turn."""
    curated_paths: tuple[str, ...]
    retained_turn_numbers: tuple[int, ...] | None
    context_summary: str          # truncated context block
    tool_calls_used: int
    turn_number: int
    timestamp: float = field(default_factory=time.time)


# session_id → last successful snapshot
_cache: dict[str, CuratorSnapshot] = {}

# session_id → last background pass briefing
_briefing_cache: dict[str, SessionBriefing] = {}


def cache_snapshot(session_id: str, snapshot: CuratorSnapshot) -> None:
    """Store the latest curator snapshot for a session."""
    _cache[session_id] = snapshot


def get_snapshot(session_id: str) -> CuratorSnapshot | None:
    """Retrieve the cached curator snapshot, or None if absent."""
    return _cache.get(session_id)


def clear_snapshot(session_id: str) -> None:
    """Remove cached snapshot for a session (e.g. on session end)."""
    _cache.pop(session_id, None)


# ---------------------------------------------------------------------------
# Briefing cache — two-pass curator
# ---------------------------------------------------------------------------

def cache_briefing(session_id: str, briefing: SessionBriefing) -> None:
    """Store the background pass briefing for a session."""
    _briefing_cache[session_id] = briefing


def get_briefing(session_id: str) -> SessionBriefing | None:
    """Retrieve the cached briefing, or None if absent."""
    return _briefing_cache.get(session_id)


def is_briefing_fresh(session_id: str, current_turn: int) -> bool:
    """Check if the cached briefing is fresh enough for the inline pass.

    A briefing is considered fresh when it was built after the previous turn
    (source_turn >= current_turn - 1). This means it was generated by the
    background pass that ran after the last user request.
    """
    briefing = _briefing_cache.get(session_id)
    if briefing is None:
        return False
    return briefing.source_turn >= current_turn - 1


def clear_briefing(session_id: str) -> None:
    """Remove cached briefing for a session."""
    _briefing_cache.pop(session_id, None)


# ---------------------------------------------------------------------------
# Background pass task guard — one in-flight per session
# ---------------------------------------------------------------------------

_bg_tasks: dict[str, asyncio.Task] = {}


def swap_background_task(session_id: str, task: asyncio.Task) -> None:
    """Register a new background pass task, cancelling any in-flight one.

    Ensures at most one background pass runs per session at a time.
    Cancelled tasks see ``CancelledError`` and exit cleanly.
    """
    old = _bg_tasks.pop(session_id, None)
    if old is not None and not old.done():
        old.cancel()

    _bg_tasks[session_id] = task
    task.add_done_callback(lambda t: _bg_tasks.pop(session_id, None))


def cancel_background_task(session_id: str) -> None:
    """Cancel the in-flight background pass for a session, if any."""
    task = _bg_tasks.pop(session_id, None)
    if task is not None and not task.done():
        task.cancel()
